name: sandbox

on: 
  workflow_dispatch:
    inputs:
      envionment:
        description: "Environment"
        required: true


jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Set output example
        id: set_output_example
        run: echo "username=nikita" >> $GITHUB_OUTPUT
      - name: Log output example
        run: echo "name is ${{ steps.set_output_example.outputs.username }}"
  hello2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ inputs.envionment }} event."
  publish:
    needs: [hello2]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: publish
        run: |
          echo 'publishing'
  staging:
    needs: [hello2]
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: publish
        run: |
          echo 'publishing'