name: Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  tests:
    runs-on: ubuntu-latest
    container: node:22
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: "postgresql://testuser:testpass@postgres:5432/testdb?schema=public"

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - name: lint
        run: npm run lint
      - name: apply migrations
        run: npx prisma migrate deploy
      - name: check migrations
        run: |
          STATUS=$(npx prisma migrate status)
          if [[ $STATUS == *"Database schema is up to date"* ]]; then
            echo "Migrations verified successfully"
          else
            echo "Migrations verification failed"
            exit 1
          fi

